[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sbt_rating = "J7Z69XPB9JDFRMcQKUxg5aUq8gAtJo2upbX8V8h8RaVh"


[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
